services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    container_name: services-postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 54320:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: services-api
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
      POSTGRES_HOST: services-postgres
      POSTGRES_SCHEMA: public
      API_KEY: supersecret
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
